version: "3"
services:
  dobby_mariadb:
    container_name: dobby_mariadb
    image: mariadb:10
    restart: always
    ports:
      - 3305:3306
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - mariadb:/var/lib/mysql
    env_file:
      - .env
  dobby_api:
    container_name: dobby_api
    build:
      context: ./api
    restart: always
    depends_on:
      - dobby_mariadb
    env_file:
      - .env
    volumes:
      - ./api/logs:/app/api/logs
      - /app/api/node_modules
  dobby_nginx:
    container_name: dobby_nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - dobby_api
volumes:
  mariadb:
