export const parameter: { [key: string]: string } = {
  social_id: 'social_id',
  social_type: 'social_type',
  user_name: 'user_name',
  profile_image_url: 'profile_image_url',
  profile_color: 'profile_color',
  authorize_code: 'authorize_code',
  refresh_token: 'refresh_token',
  group_title: 'group_title',
  invite_code: 'invite_code',
  group_id: 'group_id',
  category_title: 'category_title',
  category_id: 'category_id',
  task_title: 'task_title',
  repeat_cycle: 'repeat_cycle',
  memo: 'memo',
  notice_available: 'notice_available',
  end_repeat_at: 'end_repeat_at',
  excute_at: 'excute_at',
  add_user_ids: 'add_user_ids',
  delete_user_ids: 'delete_user_ids',
};
